### ISSUE TITLE
init.lua

### ISSUE THREAD

**Issue by max397574** [fitrh/init.nvim#1]
Could you please add an init.lua @fitrh ? 
it seems like the example one doesn't work

**Comment by fitrh** [comment]
Sorry, what do you means it doesn't work ?

My workflow in a new machine is to copy `init.lua.example` into `init.lua`

**Comment by fitrh** [comment]
> My workflow in a new machine is to copy init.lua.example into init.lua

This is meant to give me more flexibility to have a different `init.lua` for each machine in case it needs a bit adjustment

**Comment by max397574** [comment]
when I just clone the config it doesn't work
`PackerSync` is not a command

**Comment by max397574** [comment]
afaict you'd need to require `config.plugin.packer`

**Comment by fitrh** [comment]
I have the following script to setup this config on new machine

> setup.sh

```sh
#!/usr/bin/env sh

cp init.lua.example init.lua &&
    nvim --headless \
        -c 'autocmd User PackerComplete quitall' \
        -c 'lua require("config.plugin.packer")' \
        -c 'PackerSync'
```

> compile.sh

```sh
#!/usr/bin/env sh

nvim --headless \
    -c 'autocmd User PackerCompileDone quitall' \
    -c 'lua require("config.plugin.packer")' \
    -c 'PackerCompile'
```

**Comment by fitrh** [comment]
> afaict you'd need to require `config.plugin.packer`

I'm didn't include this module on my init file since **_plugin management_** isn't something I always need in the middle of work.

I only need packer when I want to install or update plugins, or there are some changes to plugins `packerspec.lua` that require recompilation, so id I need them, I run `:lua require('config.plugin.packer')` and then call the `:Packer*` things.

**Comment by max397574** [comment]
oh I see
with those scripts it makes sense
